import Color from 'helpers/ColorSchemaParser/color-value';

const pairs = [
  ['windowBg', [new Color([255, 255, 255, 255])]],
  ['windowFg', [new Color([0, 0, 0, 255])]],
  ['windowBgOver', [new Color([241, 241, 241, 255])]],
  ['windowBgRipple', [new Color([229, 229, 229, 255])]],
  ['windowFgOver', ['windowFg']],
  ['windowSubTextFg', [new Color([153, 153, 153, 255])]],
  ['windowSubTextFgOver', [new Color([145, 145, 145, 255])]],
  ['windowBoldFg', [new Color([34, 34, 34, 255])]],
  ['windowBoldFgOver', [new Color([34, 34, 34, 255])]],
  ['windowBgActive', [new Color([64, 167, 227, 255])]],
  ['windowFgActive', [new Color([255, 255, 255, 255])]],
  ['windowActiveTextFg', [new Color([22, 138, 205, 255])]],
  ['windowShadowFg', [new Color([0, 0, 0, 255])]],
  ['windowShadowFgFallback', [new Color([241, 241, 241, 255])]],
  ['shadowFg', [new Color([0, 0, 0, 24])]],
  ['slideFadeOutBg', [new Color([0, 0, 0, 60])]],
  ['slideFadeOutShadowFg', ['windowShadowFg']],
  ['imageBg', [new Color([0, 0, 0, 255])]],
  ['imageBgTransparent', [new Color([255, 255, 255, 255])]],
  ['activeButtonBg', ['windowBgActive']],
  ['activeButtonBgOver', [new Color([57, 165, 219, 255])]],
  ['activeButtonBgRipple', [new Color([32, 149, 208, 255])]],
  ['activeButtonFg', ['windowFgActive']],
  ['activeButtonFgOver', ['activeButtonFg']],
  ['activeButtonSecondaryFg', [new Color([204, 238, 255, 255])]],
  ['activeButtonSecondaryFgOver', ['activeButtonSecondaryFg']],
  ['activeLineFg', [new Color([55, 161, 222, 255])]],
  ['activeLineFgError', [new Color([228, 131, 131, 255])]],
  ['lightButtonBg', ['windowBg']],
  ['lightButtonBgOver', [new Color([227, 241, 250, 255])]],
  ['lightButtonBgRipple', [new Color([201, 228, 246, 255])]],
  ['lightButtonFg', ['windowActiveTextFg']],
  ['lightButtonFgOver', ['lightButtonFg']],
  ['attentionButtonFg', [new Color([209, 78, 78, 255])]],
  ['attentionButtonFgOver', [new Color([209, 78, 78, 255])]],
  ['attentionButtonBgOver', [new Color([252, 223, 222, 255])]],
  ['attentionButtonBgRipple', [new Color([244, 195, 194, 255])]],
  ['outlineButtonBg', ['windowBg']],
  ['outlineButtonBgOver', ['lightButtonBgOver']],
  ['outlineButtonOutlineFg', ['windowBgActive']],
  ['outlineButtonBgRipple', ['lightButtonBgRipple']],
  ['menuBg', ['windowBg']],
  ['menuBgOver', ['windowBgOver']],
  ['menuBgRipple', ['windowBgRipple']],
  ['menuIconFg', [new Color([168, 168, 168, 255])]],
  ['menuIconFgOver', [new Color([153, 153, 153, 255])]],
  ['menuSubmenuArrowFg', [new Color([55, 55, 55, 255])]],
  ['menuFgDisabled', [new Color([204, 204, 204, 255])]],
  ['menuSeparatorFg', [new Color([241, 241, 241, 255])]],
  ['scrollBarBg', [new Color([0, 0, 0, 83])]],
  ['scrollBarBgOver', [new Color([0, 0, 0, 122])]],
  ['scrollBg', [new Color([0, 0, 0, 26])]],
  ['scrollBgOver', [new Color([0, 0, 0, 44])]],
  ['smallCloseIconFg', [new Color([199, 199, 199, 255])]],
  ['smallCloseIconFgOver', [new Color([163, 163, 163, 255])]],
  ['radialFg', ['windowFgActive']],
  ['radialBg', [new Color([0, 0, 0, 86])]],
  ['placeholderFg', ['windowSubTextFg']],
  ['placeholderFgActive', [new Color([170, 170, 170, 255])]],
  ['inputBorderFg', [new Color([224, 224, 224, 255])]],
  ['filterInputBorderFg', [new Color([84, 195, 243, 255])]],
  ['filterInputActiveBg', ['windowBg']],
  ['filterInputInactiveBg', ['windowBgOver']],
  ['checkboxFg', [new Color([179, 179, 179, 255])]],
  ['botKbBg', ['menuBgOver']],
  ['botKbDownBg', ['menuBgRipple']],
  ['botKbColor', ['windowBoldFgOver']],
  ['sliderBgInactive', [new Color([225, 234, 239, 255])]],
  ['sliderBgActive', ['windowBgActive']],
  ['tooltipBg', [new Color([238, 242, 245, 255])]],
  ['tooltipFg', [new Color([93, 108, 128, 255])]],
  ['tooltipBorderFg', [new Color([201, 209, 219, 255])]],
  ['titleShadow', [new Color([0, 0, 0, 3])]],
  ['titleBg', ['windowBgOver']],
  ['titleBgActive', ['titleBg']],
  ['titleButtonBg', ['titleBg']],
  ['titleButtonFg', [new Color([171, 171, 171, 255])]],
  ['titleButtonBgOver', [new Color([229, 229, 229, 255])]],
  ['titleButtonFgOver', [new Color([154, 154, 154, 255])]],
  ['titleButtonBgActive', ['titleButtonBg']],
  ['titleButtonFgActive', ['titleButtonFg']],
  ['titleButtonBgActiveOver', ['titleButtonBgOver']],
  ['titleButtonFgActiveOver', ['titleButtonFgOver']],
  ['titleButtonCloseBg', ['titleButtonBg']],
  ['titleButtonCloseFg', ['titleButtonFg']],
  ['titleButtonCloseBgOver', [new Color([232, 17, 35, 255])]],
  ['titleButtonCloseFgOver', ['windowFgActive']],
  ['titleButtonCloseBgActive', ['titleButtonCloseBg']],
  ['titleButtonCloseFgActive', ['titleButtonCloseFg']],
  ['titleButtonCloseBgActiveOver', ['titleButtonCloseBgOver']],
  ['titleButtonCloseFgActiveOver', ['titleButtonCloseFgOver']],
  ['titleFg', [new Color([172, 172, 172, 255])]],
  ['titleFgActive', [new Color([62, 60, 62, 255])]],
  ['trayCounterBg', [new Color([242, 60, 52, 255])]],
  ['trayCounterBgMute', [new Color([136, 136, 136, 255])]],
  ['trayCounterFg', [new Color([255, 255, 255, 255])]],
  ['trayCounterBgMacInvert', [new Color([255, 255, 255, 255])]],
  ['trayCounterFgMacInvert', [new Color([255, 255, 255, 1])]],
  ['layerBg', [new Color([0, 0, 0, 127])]],
  ['cancelIconFg', ['menuIconFg']],
  ['cancelIconFgOver', ['menuIconFgOver']],
  ['boxBg', ['windowBg']],
  ['boxTextFg', ['windowFg']],
  ['boxTextFgGood', [new Color([74, 180, 74, 255])]],
  ['boxTextFgError', [new Color([216, 77, 77, 255])]],
  ['boxTitleFg', [new Color([64, 64, 64, 255])]],
  ['boxSearchBg', ['boxBg']],
  ['boxTitleAdditionalFg', [new Color([128, 128, 128, 255])]],
  ['boxTitleCloseFg', ['cancelIconFg']],
  ['boxTitleCloseFgOver', ['cancelIconFgOver']],
  ['membersAboutLimitFg', ['windowSubTextFgOver']],
  ['contactsBg', ['windowBg']],
  ['contactsBgOver', ['windowBgOver']],
  ['contactsNameFg', ['boxTextFg']],
  ['contactsStatusFg', ['windowSubTextFg']],
  ['contactsStatusFgOver', ['windowSubTextFgOver']],
  ['contactsStatusFgOnline', ['windowActiveTextFg']],
  ['photoCropFadeBg', ['layerBg']],
  ['photoCropPointFg', [new Color([255, 255, 255, 127])]],
  ['callArrowFg', [new Color([42, 179, 42, 255]), 'boxTextFgGood']],
  ['callArrowMissedFg', [new Color([221, 91, 74, 255]), 'boxTextFgError']],
  ['introBg', ['windowBg']],
  ['introTitleFg', ['windowBoldFg']],
  ['introDescriptionFg', ['windowSubTextFg']],
  ['introErrorFg', ['windowSubTextFg']],
  ['introCoverTopBg', [new Color([15, 137, 208, 255])]],
  ['introCoverBottomBg', [new Color([57, 176, 240, 255])]],
  ['introCoverIconsFg', [new Color([94, 198, 255, 255])]],
  ['introCoverPlaneTrace', [new Color([94, 198, 255, 105])]],
  ['introCoverPlaneInner', [new Color([198, 216, 232, 255])]],
  ['introCoverPlaneOuter', [new Color([161, 190, 212, 255])]],
  ['introCoverPlaneTop', [new Color([255, 255, 255, 255])]],
  ['dialogsMenuIconFg', ['menuIconFg']],
  ['dialogsMenuIconFgOver', ['menuIconFgOver']],
  ['dialogsBg', ['windowBg']],
  ['dialogsNameFg', ['windowBoldFg']],
  ['dialogsChatIconFg', ['dialogsNameFg']],
  ['dialogsDateFg', ['windowSubTextFg']],
  ['dialogsTextFg', ['windowSubTextFg']],
  ['dialogsTextFgService', ['windowActiveTextFg']],
  ['dialogsDraftFg', [new Color([221, 75, 57, 255])]],
  ['dialogsVerifiedIconBg', ['windowBgActive']],
  ['dialogsVerifiedIconFg', ['windowFgActive']],
  ['dialogsSendingIconFg', [new Color([193, 193, 193, 255])]],
  ['dialogsSentIconFg', [new Color([93, 196, 82, 255])]],
  ['dialogsUnreadBg', ['windowBgActive']],
  ['dialogsUnreadBgMuted', [new Color([187, 187, 187, 255])]],
  ['dialogsUnreadFg', ['windowFgActive']],
  ['dialogsBgOver', ['windowBgOver']],
  ['dialogsNameFgOver', ['windowBoldFgOver']],
  ['dialogsChatIconFgOver', ['dialogsNameFgOver']],
  ['dialogsDateFgOver', ['windowSubTextFgOver']],
  ['dialogsTextFgOver', ['windowSubTextFgOver']],
  ['dialogsTextFgServiceOver', ['dialogsTextFgService']],
  ['dialogsDraftFgOver', ['dialogsDraftFg']],
  ['dialogsVerifiedIconBgOver', ['dialogsVerifiedIconBg']],
  ['dialogsVerifiedIconFgOver', ['dialogsVerifiedIconFg']],
  ['dialogsSendingIconFgOver', ['dialogsSendingIconFg']],
  ['dialogsSentIconFgOver', ['dialogsSentIconFg']],
  ['dialogsUnreadBgOver', ['dialogsUnreadBg']],
  ['dialogsUnreadBgMutedOver', ['dialogsUnreadBgMuted']],
  ['dialogsUnreadFgOver', ['dialogsUnreadFg']],
  ['dialogsBgActive', [new Color([65, 159, 217, 255])]],
  ['dialogsNameFgActive', ['windowFgActive']],
  ['dialogsChatIconFgActive', ['dialogsNameFgActive']],
  ['dialogsDateFgActive', ['windowFgActive']],
  ['dialogsTextFgActive', ['windowFgActive']],
  ['dialogsTextFgServiceActive', ['dialogsTextFgActive']],
  ['dialogsDraftFgActive', [new Color([198, 225, 247, 255])]],
  ['dialogsVerifiedIconBgActive', ['dialogsTextFgActive']],
  ['dialogsVerifiedIconFgActive', ['dialogsBgActive']],
  ['dialogsSendingIconFgActive', [new Color([255, 255, 255, 153])]],
  ['dialogsSentIconFgActive', ['dialogsTextFgActive']],
  ['dialogsUnreadBgActive', ['dialogsTextFgActive']],
  ['dialogsUnreadBgMutedActive', ['dialogsDraftFgActive']],
  ['dialogsUnreadFgActive', ['dialogsBgActive']],
  ['dialogsRippleBg', ['windowBgRipple']],
  ['dialogsRippleBgActive', ['activeButtonBgRipple']],
  ['dialogsForwardBg', ['dialogsBgActive']],
  ['dialogsForwardFg', ['dialogsNameFgActive']],
  ['searchedBarBg', ['windowBgOver']],
  ['searchedBarFg', ['windowSubTextFgOver']],
  ['topBarBg', ['windowBg']],
  ['emojiPanBg', ['windowBg']],
  ['emojiPanCategories', [new Color([247, 247, 247, 255]), 'windowBg']],
  ['emojiPanHeaderFg', ['windowSubTextFg']],
  ['emojiPanHeaderBg', [new Color([255, 255, 255, 242]), 'emojiPanBg']],
  ['emojiIconFg', ['checkboxFg']],
  ['emojiIconFgActive', ['windowBgActive']],
  ['stickerPanDeleteBg', [new Color([0, 0, 0, 204])]],
  ['stickerPanDeleteFg', ['windowFgActive']],
  ['stickerPreviewBg', [new Color([255, 255, 255, 176])]],
  ['historyTextInFg', ['windowFg']],
  ['historyTextInFgSelected', ['historyTextInFg']],
  ['historyTextOutFg', ['windowFg']],
  ['historyTextOutFgSelected', ['historyTextOutFg']],
  ['historyLinkInFg', ['windowActiveTextFg']],
  ['historyLinkInFgSelected', ['historyLinkInFg']],
  ['historyLinkOutFg', ['windowActiveTextFg']],
  ['historyLinkOutFgSelected', ['historyLinkOutFg']],
  ['historyFileNameInFg', ['historyTextInFg']],
  ['historyFileNameInFgSelected', ['historyFileNameInFg']],
  ['historyFileNameOutFg', ['historyTextOutFg']],
  ['historyFileNameOutFgSelected', ['historyFileNameOutFg']],
  ['historyOutIconFg', ['dialogsSentIconFg']],
  ['historyOutIconFgSelected', [new Color([77, 167, 159, 255])]],
  ['historyIconFgInverted', ['windowFgActive']],
  ['historySendingOutIconFg', [new Color([152, 210, 146, 255])]],
  ['historySendingInIconFg', [new Color([160, 173, 181, 255])]],
  ['historySendingInvertedIconFg', [new Color([255, 255, 255, 200])]],
  ['historyCallArrowInFg', ['callArrowFg']],
  ['historyCallArrowInFgSelected', ['callArrowFg']],
  ['historyCallArrowMissedInFg', ['callArrowMissedFg']],
  ['historyCallArrowMissedInFgSelected', ['callArrowMissedFg']],
  ['historyCallArrowOutFg', ['historyCallArrowInFg']],
  ['historyCallArrowOutFgSelected', ['historyCallArrowInFgSelected']],
  ['historyUnreadBarBg', [new Color([252, 251, 250, 255])]],
  ['historyUnreadBarBorder', ['shadowFg']],
  ['historyUnreadBarFg', [new Color([83, 139, 180, 255])]],
  ['historyForwardChooseBg', [new Color([0, 0, 0, 76])]],
  ['historyForwardChooseFg', ['windowFgActive']],
  ['historyPeer1NameFg', [new Color([192, 61, 51, 255])]],
  ['historyPeer1NameFgSelected', ['historyPeer1NameFg']],
  ['historyPeer1UserpicBg', [new Color([225, 112, 118, 255])]],
  ['historyPeer2NameFg', [new Color([79, 173, 45, 255])]],
  ['historyPeer2NameFgSelected', ['historyPeer2NameFg']],
  ['historyPeer2UserpicBg', [new Color([123, 200, 98, 255])]],
  ['historyPeer3NameFg', [new Color([208, 147, 6, 255])]],
  ['historyPeer3NameFgSelected', ['historyPeer3NameFg']],
  ['historyPeer3UserpicBg', [new Color([229, 202, 119, 255])]],
  ['historyPeer4NameFg', ['windowActiveTextFg']],
  ['historyPeer4NameFgSelected', ['historyPeer4NameFg']],
  ['historyPeer4UserpicBg', [new Color([101, 170, 221, 255])]],
  ['historyPeer5NameFg', [new Color([133, 68, 214, 255])]],
  ['historyPeer5NameFgSelected', ['historyPeer5NameFg']],
  ['historyPeer5UserpicBg', [new Color([166, 149, 231, 255])]],
  ['historyPeer6NameFg', [new Color([205, 64, 115, 255])]],
  ['historyPeer6NameFgSelected', ['historyPeer6NameFg']],
  ['historyPeer6UserpicBg', [new Color([238, 122, 174, 255])]],
  ['historyPeer7NameFg', [new Color([41, 150, 173, 255])]],
  ['historyPeer7NameFgSelected', ['historyPeer7NameFg']],
  ['historyPeer7UserpicBg', [new Color([110, 201, 203, 255])]],
  ['historyPeer8NameFg', [new Color([206, 103, 27, 255])]],
  ['historyPeer8NameFgSelected', ['historyPeer8NameFg']],
  ['historyPeer8UserpicBg', [new Color([250, 167, 116, 255])]],
  ['historyPeerUserpicFg', ['windowFgActive']],
  ['historyScrollBarBg', [new Color([81, 124, 65, 122])]],
  ['historyScrollBarBgOver', [new Color([81, 124, 65, 188])]],
  ['historyScrollBg', [new Color([81, 124, 65, 76])]],
  ['historyScrollBgOver', [new Color([81, 124, 65, 107])]],
  ['msgInBg', ['windowBg']],
  ['msgInBgSelected', [new Color([194, 220, 242, 255])]],
  ['msgOutBg', [new Color([239, 253, 222, 255])]],
  ['msgOutBgSelected', [new Color([183, 219, 219, 255])]],
  ['msgSelectOverlay', [new Color([53, 140, 212, 76])]],
  ['msgStickerOverlay', [new Color([53, 140, 212, 127])]],
  ['msgInServiceFg', ['windowActiveTextFg']],
  ['msgInServiceFgSelected', ['windowActiveTextFg']],
  ['msgOutServiceFg', [new Color([58, 142, 38, 255])]],
  ['msgOutServiceFgSelected', [new Color([54, 117, 112, 255])]],
  ['msgInShadow', [new Color([116, 142, 162, 41])]],
  ['msgInShadowSelected', [new Color([84, 141, 187, 41])]],
  ['msgOutShadow', [new Color([58, 195, 71, 64])]],
  ['msgOutShadowSelected', [new Color([55, 167, 142, 64])]],
  ['msgInDateFg', [new Color([160, 172, 182, 255])]],
  ['msgInDateFgSelected', [new Color([106, 156, 197, 255])]],
  ['msgOutDateFg', [new Color([108, 194, 100, 255])]],
  ['msgOutDateFgSelected', [new Color([80, 167, 156, 255])]],
  ['msgServiceFg', ['windowFgActive']],
  ['msgServiceBg', [new Color([81, 124, 65, 127])]],
  ['msgServiceBgSelected', [new Color([150, 179, 139, 162])]],
  ['msgInReplyBarColor', ['activeLineFg']],
  ['msgInReplyBarSelColor', ['activeLineFg']],
  ['msgOutReplyBarColor', ['historyOutIconFg']],
  ['msgOutReplyBarSelColor', ['historyOutIconFgSelected']],
  ['msgImgReplyBarColor', ['msgServiceFg']],
  ['msgInMonoFg', [new Color([78, 115, 145, 255])]],
  ['msgOutMonoFg', [new Color([70, 145, 101, 255])]],
  ['msgInMonoFgSelected', ['msgInMonoFg']],
  ['msgOutMonoFgSelected', ['msgOutMonoFg']],
  ['msgDateImgFg', ['msgServiceFg']],
  ['msgDateImgBg', [new Color([0, 0, 0, 84])]],
  ['msgDateImgBgOver', [new Color([0, 0, 0, 116])]],
  ['msgDateImgBgSelected', [new Color([28, 74, 113, 135])]],
  ['msgFileThumbLinkInFg', ['lightButtonFg']],
  ['msgFileThumbLinkInFgSelected', ['lightButtonFgOver']],
  ['msgFileThumbLinkOutFg', [new Color([94, 186, 91, 255])]],
  ['msgFileThumbLinkOutFgSelected', [new Color([49, 162, 152, 255])]],
  ['msgFileInBg', ['windowBgActive']],
  ['msgFileInBgOver', [new Color([78, 173, 227, 255])]],
  ['msgFileInBgSelected', [new Color([81, 163, 211, 255])]],
  ['msgFileOutBg', [new Color([120, 198, 127, 255])]],
  ['msgFileOutBgOver', [new Color([107, 194, 114, 255])]],
  ['msgFileOutBgSelected', [new Color([95, 179, 137, 255])]],
  ['msgFile1Bg', [new Color([114, 177, 223, 255])]],
  ['msgFile1BgDark', [new Color([92, 158, 206, 255])]],
  ['msgFile1BgOver', [new Color([82, 148, 196, 255])]],
  ['msgFile1BgSelected', [new Color([80, 153, 208, 255])]],
  ['msgFile2Bg', [new Color([97, 185, 110, 255])]],
  ['msgFile2BgDark', [new Color([77, 168, 89, 255])]],
  ['msgFile2BgOver', [new Color([68, 160, 80, 255])]],
  ['msgFile2BgSelected', [new Color([70, 160, 126, 255])]],
  ['msgFile3Bg', [new Color([228, 114, 114, 255])]],
  ['msgFile3BgDark', [new Color([205, 91, 94, 255])]],
  ['msgFile3BgOver', [new Color([195, 81, 84, 255])]],
  ['msgFile3BgSelected', [new Color([159, 106, 130, 255])]],
  ['msgFile4Bg', [new Color([239, 194, 116, 255])]],
  ['msgFile4BgDark', [new Color([230, 165, 97, 255])]],
  ['msgFile4BgOver', [new Color([220, 156, 90, 255])]],
  ['msgFile4BgSelected', [new Color([177, 157, 132, 255])]],
  ['historyFileInIconFg', ['msgInBg']],
  ['historyFileInIconFgSelected', ['msgInBgSelected']],
  ['historyFileInRadialFg', ['historyFileInIconFg']],
  ['historyFileInRadialFgSelected', ['historyFileInIconFgSelected']],
  ['historyFileOutIconFg', ['msgOutBg']],
  ['historyFileOutIconFgSelected', ['msgOutBgSelected']],
  ['historyFileOutRadialFg', ['historyFileOutIconFg']],
  ['historyFileOutRadialFgSelected', ['historyFileOutIconFgSelected']],
  ['historyFileThumbIconFg', ['msgInBg']],
  ['historyFileThumbIconFgSelected', ['msgInBgSelected']],
  ['historyFileThumbRadialFg', ['historyFileThumbIconFg']],
  ['historyFileThumbRadialFgSelected', ['historyFileThumbIconFgSelected']],
  ['historyVideoMessageProgressFg', ['historyFileThumbIconFg']],
  ['msgWaveformInActive', ['windowBgActive']],
  ['msgWaveformInActiveSelected', [new Color([81, 163, 211, 255])]],
  ['msgWaveformInInactive', [new Color([212, 222, 230, 255])]],
  ['msgWaveformInInactiveSelected', [new Color([156, 193, 225, 255])]],
  ['msgWaveformOutActive', [new Color([120, 198, 127, 255])]],
  ['msgWaveformOutActiveSelected', [new Color([107, 173, 173, 255])]],
  ['msgWaveformOutInactive', [new Color([179, 226, 180, 255])]],
  ['msgWaveformOutInactiveSelected', [new Color([145, 195, 195, 255])]],
  ['msgBotKbOverBgAdd', [new Color([255, 255, 255, 32])]],
  ['msgBotKbIconFg', ['msgServiceFg']],
  ['msgBotKbRippleBg', [new Color([0, 0, 0, 32])]],
  ['mediaInFg', ['msgInDateFg']],
  ['mediaInFgSelected', ['msgInDateFgSelected']],
  ['mediaOutFg', ['msgOutDateFg']],
  ['mediaOutFgSelected', ['msgOutDateFgSelected']],
  ['youtubePlayIconBg', [new Color([232, 49, 49, 200])]],
  ['youtubePlayIconFg', ['windowFgActive']],
  ['videoPlayIconBg', [new Color([0, 0, 0, 127])]],
  ['videoPlayIconFg', [new Color([255, 255, 255, 255])]],
  ['toastBg', [new Color([0, 0, 0, 178])]],
  ['toastFg', ['windowFgActive']],
  ['reportSpamBg', ['emojiPanHeaderBg']],
  ['reportSpamFg', ['windowFg']],
  ['historyToDownBg', ['windowBg']],
  ['historyToDownBgOver', ['windowBgOver']],
  ['historyToDownBgRipple', ['windowBgRipple']],
  ['historyToDownFg', ['menuIconFg']],
  ['historyToDownFgOver', ['menuIconFgOver']],
  ['historyToDownShadow', [new Color([0, 0, 0, 64])]],
  ['historyComposeAreaBg', ['msgInBg']],
  ['historyComposeAreaFg', ['historyTextInFg']],
  ['historyComposeAreaFgService', ['msgInDateFg']],
  ['historyComposeIconFg', ['menuIconFg']],
  ['historyComposeIconFgOver', ['menuIconFgOver']],
  ['historySendIconFg', ['windowBgActive']],
  ['historySendIconFgOver', ['windowBgActive']],
  ['historyPinnedBg', ['historyComposeAreaBg']],
  ['historyReplyBg', ['historyComposeAreaBg']],
  ['historyReplyIconFg', ['windowBgActive']],
  ['historyReplyCancelFg', ['cancelIconFg']],
  ['historyReplyCancelFgOver', ['cancelIconFgOver']],
  ['historyComposeButtonBg', ['historyComposeAreaBg']],
  ['historyComposeButtonBgOver', ['windowBgOver']],
  ['historyComposeButtonBgRipple', ['windowBgRipple']],
  ['overviewCheckBg', [new Color([0, 0, 0, 64])]],
  ['overviewCheckBgActive', ['windowBgActive']],
  ['overviewCheckBorder', ['windowBg']],
  ['overviewCheckFg', ['windowBg']],
  ['overviewCheckFgActive', ['windowBg']],
  ['overviewPhotoSelectOverlay', [new Color([64, 172, 227, 51])]],
  ['profileStatusFgOver', [new Color([124, 153, 178, 255])]],
  ['profileVerifiedCheckBg', ['windowBgActive']],
  ['profileVerifiedCheckFg', ['windowFgActive']],
  ['profileAdminStartFg', ['windowBgActive']],
  ['profileAdminStarFgOver', ['profileAdminStartFg']],
  ['profileOtherAdminStarFg', ['windowSubTextFg']],
  ['profileOtherAdminStarFgOver', ['profileStatusFgOver']],
  ['notificationsBoxMonitorFg', ['windowFg']],
  ['notificationsBoxScreenBg', ['dialogsBgActive']],
  ['notificationSampleUserpicFg', ['windowBgActive']],
  [
    'notificationSampleCloseFg',
    [new Color([215, 215, 215, 255]), 'windowSubTextFg'],
  ],
  [
    'notificationSampleTextFg',
    [new Color([215, 215, 215, 255]), 'windowSubTextFg'],
  ],
  [
    'notificationSampleNameFg',
    [new Color([147, 147, 147, 255]), 'windowSubTextFg'],
  ],
  ['changePhoneSimcardFrom', ['notificationSampleTextFg']],
  ['changePhoneSimcardTo', ['notificationSampleNameFg']],
  ['mainMenuBg', ['windowBg']],
  ['mainMenuCoverBg', ['dialogsBgActive']],
  ['mainMenuCoverFg', ['windowFgActive']],
  ['mainMenuCloudFg', ['activeButtonFg']],
  [
    'mainMenuCloudBg',
    [new Color([39, 133, 191, 255]), 'activeButtonBgRipple'],
  ],
  ['mediaPlayerBg', ['windowBg']],
  ['mediaPlayerActiveFg', ['windowBgActive']],
  ['mediaPlayerInactiveFg', ['sliderBgInactive']],
  ['mediaPlayerDisabledFg', [new Color([157, 209, 239, 255])]],
  ['mediaviewFileBg', ['windowBg']],
  ['mediaviewFileNameFg', ['windowFg']],
  ['mediaviewFileSizeFg', ['windowSubTextFg']],
  ['mediaviewFileRedCornerFg', [new Color([213, 89, 89, 255])]],
  ['mediaviewFileYellowCornerFg', [new Color([232, 166, 89, 255])]],
  ['mediaviewFileGreenCornerFg', [new Color([73, 169, 87, 255])]],
  ['mediaviewFileBlueCornerFg', [new Color([89, 157, 207, 255])]],
  ['mediaviewFileExtFg', ['activeButtonFg']],
  ['mediaviewMenuBg', [new Color([56, 56, 56, 255])]],
  ['mediaviewMenuBgOver', [new Color([80, 80, 80, 255])]],
  ['mediaviewMenuBgRipple', [new Color([103, 103, 103, 255])]],
  ['mediaviewMenuFg', ['windowFgActive']],
  ['mediaviewBg', [new Color([34, 34, 34, 235])]],
  ['mediaviewVideoBg', ['imageBg']],
  ['mediaviewControlBg', [new Color([0, 0, 0, 60])]],
  ['mediaviewControlFg', ['windowFgActive']],
  ['mediaviewCaptionBg', [new Color([17, 17, 17, 128])]],
  ['mediaviewCaptionFg', ['mediaviewControlFg']],
  ['mediaviewTextLinkFg', [new Color([145, 217, 255, 255])]],
  ['mediaviewSaveMsgBg', ['toastBg']],
  ['mediaviewSaveMsgFg', ['toastFg']],
  ['mediaviewPlaybackActive', [new Color([199, 199, 199, 255])]],
  ['mediaviewPlaybackInactive', [new Color([37, 37, 37, 255])]],
  ['mediaviewPlaybackActiveOver', [new Color([255, 255, 255, 255])]],
  ['mediaviewPlaybackInactiveOver', [new Color([71, 71, 71, 255])]],
  ['mediaviewPlaybackProgressFg', [new Color([255, 255, 255, 199])]],
  ['mediaviewPlaybackIconFg', ['mediaviewPlaybackActive']],
  ['mediaviewPlaybackIconFgOver', ['mediaviewPlaybackActiveOver']],
  ['mediaviewTransparentBg', [new Color([255, 255, 255, 255])]],
  ['mediaviewTransparentFg', [new Color([204, 204, 204, 255])]],
  ['notificationBg', ['windowBg']],
  ['callBg', [new Color([38, 40, 44, 242])]],
  ['callNameFg', [new Color([255, 255, 255, 255])]],
  ['callFingerprintBg', [new Color([0, 0, 0, 102])]],
  ['callStatusFg', [new Color([170, 171, 172, 255])]],
  ['callIconFg', [new Color([255, 255, 255, 255])]],
  ['callAnswerBg', [new Color([100, 193, 91, 255])]],
  ['callAnswerRipple', [new Color([82, 177, 73, 255])]],
  ['callAnswerBgOuter', [new Color([80, 235, 65, 38])]],
  ['callHangupBg', [new Color([215, 90, 90, 255])]],
  ['callHangupRipple', [new Color([192, 70, 70, 255])]],
  ['callCancelBg', [new Color([255, 255, 255, 255])]],
  ['callCancelFg', [new Color([119, 119, 119, 255])]],
  ['callCancelRipple', [new Color([241, 241, 241, 255])]],
  ['callMuteRipple', [new Color([255, 255, 255, 18])]],
  ['callBarBg', ['dialogsBgActive']],
  ['callBarMuteRipple', ['dialogsRippleBgActive']],
  [
    'callBarBgMuted',
    [new Color([143, 143, 143, 255]), 'dialogsUnreadBgMuted'],
  ],
  ['callBarUnmuteRipple', [new Color([127, 127, 127, 255]), 'shadowFg']],
  ['callBarFg', ['dialogsNameFgActive']],
  ['importantTooltipBg', ['toastBg']],
  ['importantTooltipFg', ['toastFg']],
  ['importantTooltipFgLink', ['mediaviewTextLinkFg']],
];

export default {
  meta: {
    backgroundImage: require('./background.jpg'),
    builtin: true,
  },

  pairs,
};
